version: "2"

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

services:
  web:
    restart: always
    build: ./web
    image: web
    networks:
      - reverse-proxy
      - back
    expose:
      - "${WEB_PORT}"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - "VIRTUAL_NETWORK=reverse-proxy"
      - "VIRTUAL_PORT=${WEB_PORT}"

  admin:
    restart: always
    build: ./admin
    image: admin
    networks:
      - reverse-proxy
      - back
    expose:
      - "${ADMIN_PORT}"
    ports:
      - "${ADMIN_PORT}:${ADMIN_PORT}"
    environment:
      - "VIRTUAL_NETWORK=reverse-proxy"
      - "VIRTUAL_PORT=${ADMIN_PORT}"

  donations-worker:
    restart: always
    build: ./donations-worker
    image: donations-worker
    networks:
      - back
    links:
      - mongo

  mongo:
    restart: always
    image: mongo
    networks:
      - back
    ports:
      - "27017:27017"
