version: "2"
services:
  donations-worker:
    volumes:
      - ./donations-worker:/opt/app
  admin:
    command: ["yarn", "start"]
    volumes:
      - ./admin:/opt/app
  web:
    command: ["yarn", "start"]
    volumes:
      - ./web:/opt/app
  mongo:
    volumes:
      - /data/db
