version: "2"

services:
  web:
    command: ["yarn", "start:dev"]

  admin:
    command: ["yarn", "start:dev"]

  api:
    command: ["yarn", "start:dev"]

  donations-worker:
    command: ["yarn", "start:dev"]
