version: "2"

services:
  web:
    command: ["yarn", "start:dev"]
    volumes:
      - "./web:/opt/app"

  admin:
    command: ["yarn", "start:dev"]
    volumes:
      - "./admin:/opt/app"

  api:
    command: ["yarn", "start:dev"]
    volumes:
      - "./api:/opt/app"

  donations-worker:
    command: ["yarn", "start:dev"]
    volumes:
      - "./donations-worker:/opt/app"
