version: '2'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge

services:
  web:
    restart: always
    build: ./web
    image: web
    networks:
      - reverse-proxy
      - back
    expose:
      - '${WEB_PORT}'
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    environment:
      - 'API_HOST=${API_HOST}'
      - 'API_PROTOCOL=${API_PROTOCOL}'
      - 'LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}'
      - 'LETSENCRYPT_HOST=${WEB_HOST}'
      - 'LOGGLY_TOKEN=${LOGGLY_TOKEN}'
      - 'LOGGLY_SUBDOMAIN=${LOGGLY_SUBDOMAIN}'
      - 'VIRTUAL_HOST=${WEB_HOST}'
      - 'VIRTUAL_NETWORK=reverse-proxy'
      - 'VIRTUAL_PORT=${WEB_PORT}'

  admin:
    restart: always
    build: ./admin
    image: admin
    networks:
      - reverse-proxy
      - back
    expose:
      - '${ADMIN_PORT}'
    ports:
      - '${ADMIN_PORT}:${ADMIN_PORT}'
    environment:
      - 'API_HOST=${API_HOST}'
      - 'API_PROTOCOL=${API_PROTOCOL}'
      - 'LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}'
      - 'LETSENCRYPT_HOST=${ADMIN_HOST}'
      - 'LOGGLY_TOKEN=${LOGGLY_TOKEN}'
      - 'LOGGLY_SUBDOMAIN=${LOGGLY_SUBDOMAIN}'
      - 'VIRTUAL_HOST=${ADMIN_HOST}'
      - 'VIRTUAL_NETWORK=reverse-proxy'
      - 'VIRTUAL_PORT=${ADMIN_PORT}'

  api:
    restart: always
    build: ./api
    image: api
    networks:
      - reverse-proxy
      - back
    expose:
      - '${API_PORT}'
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - 'FIREBASE_APIKEY=${FIREBASE_APIKEY}'
      - 'FIREBASE_AUTHDOMAIN=${FIREBASE_AUTHDOMAIN}'
      - 'FIREBASE_MESSAGING_SERVERKEY=${FIREBASE_MESSAGING_SERVERKEY}'
      - 'FIREBASE_PROJECTID=${FIREBASE_PROJECTID}'
      - 'LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}'
      - 'LETSENCRYPT_HOST=${API_HOST}'
      - 'LOGGLY_TOKEN=${LOGGLY_TOKEN}'
      - 'LOGGLY_SUBDOMAIN=${LOGGLY_SUBDOMAIN}'
      - 'VIRTUAL_HOST=${API_HOST}'
      - 'VIRTUAL_NETWORK=reverse-proxy'
      - 'VIRTUAL_PORT=${API_PORT}'

  donations-worker:
    restart: always
    build: ./donations-worker
    image: donations-worker
    networks:
      - back
    environment:
      - 'FIREBASE_APIKEY=${FIREBASE_APIKEY}'
      - 'FIREBASE_AUTHDOMAIN=${FIREBASE_AUTHDOMAIN}'
      - 'FIREBASE_PROJECTID=${FIREBASE_PROJECTID}'
      - 'JUSTGIVING_APP_ID=${JUSTGIVING_APP_ID}'
      - 'JUSTGIVING_PAGE=${JUSTGIVING_PAGE}'
      - 'LOGGLY_TOKEN=${LOGGLY_TOKEN}'
      - 'LOGGLY_SUBDOMAIN=${LOGGLY_SUBDOMAIN}'
      - 'POLL_INTERVAL=${POLL_INTERVAL}'
