version: "2"
services:
  web:
    restart: always
    build: ./web
    image: web
    ports:
      - "3000:3000"
    environment:
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "VIRTUAL_PORT=3000"
      - "LETSENCRYPT_TEST=true"

  admin:
    restart: always
    build: ./admin
    image: admin
    ports:
      - "3001:3001"
    environment:
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "VIRTUAL_PORT=3001"
      - "LETSENCRYPT_TEST=true"

  donations-worker:
    restart: always
    build: ./donations-worker
    image: donations-worker
    links:
      - mongo

  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates:/etc/docker-gen/templates:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
